name: Modular Security Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  snyk_scan:
    name: Snyk Dependency Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Snyk Scan
        uses: snyk/actions@v2
        with:
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  sonarcloud_scan:
    name: SonarCloud Code Analysis
    runs-on: ubuntu-latest
    needs: snyk_scan
    steps:
      - uses: actions/checkout@v3
      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  zap_scan:
    name: OWASP ZAP DAST Scan
    runs-on: ubuntu-latest
    needs: sonarcloud_scan
    steps:
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'https://172.26.160.1:8080/WebGoat'
